### ISSUE TITLE
Suggestions for clarification

### ISSUE THREAD

**Issue by jakesmolka** [microsoft/azure-health-data-services-workshop#18]
Hey, I have tried some challenges and here are some small suggestion of things I was confused by / did not directly get.

--------------------

**First**: https://github.com/microsoft/azure-health-data-services-workshop/tree/main/Challenge-04%20-%20Query%20and%20Search%20FHIR#exercise-task-6

Step 7, task 4: It might makes sense to add the clarification, that the operation is not successful as long as the first entry in the bundle is an `OperationOutcome`, stating "The search parameter 'race' is not supported for resource type 'Patient'.". Because on the first look it still returns many (all?) Patients and it could look like a successful operation. After waiting a moment and resending the request, the response is as expected.

--------------------

**Second**: https://github.com/microsoft/azure-health-data-services-workshop/tree/main/Challenge-05%20-%20Export%20and%20Anonymize%20Data#step-2-configure-storage-account-for-export

The note of Step 2 contains this part: 
> "The name of this storage account ends with "expsa". Keep in mind that you are configuring the storage account in this step (and not the FHIR service!). In the storage account, be careful not to add a role assignment to a service client or a service principal by mistake!"

It gave me the impression that in the dialogs I have to select the blob storage as target for the role assignment. In contrast to the previous sentences.
In my flow of adding the role I haven't interacted with the storage name or resource. I just gave the FHIR service the role:

As logged by an Azure notification (`fhirtrn` is the FHIR Service resource): 
> "Added Role assignment:
> xyz…hdsws/fhirtrn was added as Storage Blob Data Contributor for $resourcegroupname."

--------------------

Everything else worked great! Thanks 👍

**Comment by v-pbartley** [comment]
@jakesmolka Thanks Jake for testing the challenges and giving your feedback! I'll take a look at how we can fix these two issues you pointed out.

**Comment by v-pbartley** [comment]
Resolved
