### ISSUE TITLE
DICOM Challenge 8 Basic Setup

### ISSUE THREAD

**Issue by alritko** [microsoft/azure-health-data-services-workshop#19]
The Basic Setup steps do not align with the files referenced in the previous steps.  The Conformance_as_Postman collection no longer contains a POST AuthorizeGetToken.  Also, the variables set in the dicom-service environment do not align with the variables defined in the Conformance_as_Postman collection.  The variables in Conformance_as_Postman are pointing to a localhost URL.

**Comment by v-pbartley** [comment]
@alritko Thank you for alerting us to these changes in the Conformance_as_Postman collection for DICOM. We will make adjustments accordingly.
